import type { FocalPoint, Project, ProjectCategory, ProjectImage } from "@/types/project";

type ImageInput = {
  file: string;
  alt: string;
  caption?: string;
  focalPoint?: FocalPoint;
  width: number;
  height: number;
};

const imageSizes: Record<string, Pick<ProjectImage, "width" | "height">> = {
  "realizacja-01.jpeg": { width: 1600, height: 1200 },
  "realizacja-02.jpeg": { width: 1200, height: 1600 },
  "realizacja-03.jpeg": { width: 1600, height: 1200 },
  "realizacja-04.jpeg": { width: 1600, height: 1200 },
  "realizacja-05.jpeg": { width: 1200, height: 1600 },
  "realizacja-06.jpeg": { width: 1600, height: 1200 },
  "realizacja-07.jpeg": { width: 1600, height: 1200 },
  "realizacja-08.jpeg": { width: 2048, height: 1536 },
  "realizacja-09.jpeg": { width: 1600, height: 1200 },
  "realizacja-10.jpeg": { width: 1200, height: 1600 },
  "realizacja-11.jpeg": { width: 1600, height: 1200 },
  "realizacja-12.jpeg": { width: 1600, height: 1200 },
  "realizacja-13.jpeg": { width: 1600, height: 1200 },
  "realizacja-14.jpeg": { width: 1600, height: 1200 },
  "realizacja-15.jpeg": { width: 1200, height: 1600 },
  "realizacja-16.jpeg": { width: 2048, height: 1536 },
  "realizacja-17.jpeg": { width: 2048, height: 1536 },
  "realizacja-18.jpeg": { width: 1600, height: 1200 },
  "realizacja-19.jpeg": { width: 1600, height: 1200 },
  "realizacja-20.jpeg": { width: 1200, height: 1600 },
  "realizacja-21.jpeg": { width: 2048, height: 1536 },
  "realizacja-22.jpeg": { width: 2048, height: 1536 },
  "realizacja-23.jpeg": { width: 1600, height: 1200 },
  "realizacja-24.jpeg": { width: 1600, height: 1200 },
  "realizacja-25.jpeg": { width: 1536, height: 2048 }
};

const categoryOrder: ProjectCategory[] = [
  "Kuchnie",
  "Szafy i garderoby",
  "Łazienki",
  "Biura",
  "Lamele",
  "Zabudowy nietypowe",
  "Detale",
];

export const projectFilterCategories = ["Wszystkie", ...categoryOrder] as const;

function image(file: string, input: Omit<ImageInput, "file" | "width" | "height">, order: number): ProjectImage {
  const size = imageSizes[file];

  return {
    id: file.replace(".jpeg", ""),
    src: `/realizacje/${file}`,
    order,
    width: size.width,
    height: size.height,
    ...input,
  };
}

export const projects: Project[] = [
  {
    id: "realizacja-01",
    title: "Łazienka z ryflowaną szafką pod umywalki",
    slug: "realizacja-01",
    category: "Łazienki",
    description: "Szafka łazienkowa na wymiar z dwiema umywalkami, lustrami w łuku i ryflowanym panelem przy zabudowie.",
    coverImage: "/realizacje/realizacja-01.jpeg",
    coverFocalPoint: "center",
    tags: ["Łazienka", "Szafka pod umywalki", "Ryflowane fronty"],
    featured: true,
    order: 1,
    images: [
      image("realizacja-01.jpeg", {
        alt: "Łazienka z podwójną umywalką, ryflowaną szafką i lustrami w łuku",
        caption: "Szafka pod dwie umywalki z ryflowanym frontem i elegancką strefą luster.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-02",
    title: "Wąska kuchnia z zabudową do sufitu",
    slug: "realizacja-02",
    category: "Kuchnie",
    description: "Kompaktowa kuchnia na wymiar z wysoką zabudową, jasnym blatem roboczym i wygodnym układem wzdłuż ścian.",
    coverImage: "/realizacje/realizacja-02.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Zabudowa do sufitu", "Małe wnętrze"],
    featured: true,
    order: 2,
    images: [
      image("realizacja-02.jpeg", {
        alt: "Wąska kuchnia na wymiar z wysokimi szafkami i jasnym blatem roboczym",
        caption: "Funkcjonalna zabudowa kuchenna zaplanowana pod długie, wąskie pomieszczenie.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-03",
    title: "Biała kuchnia narożna ze strefą zmywania",
    slug: "realizacja-03",
    category: "Kuchnie",
    description: "Jasna kuchnia na wymiar z narożnym układem szafek, zlewem pod oknem i wysokim słupkiem AGD.",
    coverImage: "/realizacje/realizacja-03.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Białe fronty", "Strefa zmywania"],
    featured: true,
    order: 3,
    images: [
      image("realizacja-03.jpeg", {
        alt: "Biała kuchnia narożna z jasnym blatem, zlewem i zabudową AGD",
        caption: "Narożna zabudowa kuchenna z praktyczną strefą zmywania i miejscem na sprzęt AGD.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-04",
    title: "Biała kuchnia z jasnym blatem roboczym",
    slug: "realizacja-04",
    category: "Kuchnie",
    description: "Nowoczesna kuchnia z matowymi frontami, dyskretnymi uchwytami i dopasowaną zabudową przy zlewie.",
    coverImage: "/realizacje/realizacja-04.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Matowe fronty", "Blat roboczy"],
    featured: true,
    order: 4,
    images: [
      image("realizacja-04.jpeg", {
        alt: "Biała kuchnia na wymiar z jasnym blatem i zabudowaną strefą zlewu",
        caption: "Spójna zabudowa kuchenna z jasnym blatem i dużą ilością miejsca do pracy.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-05",
    title: "Salon z jadalnią i podświetlaną zabudową RTV",
    slug: "realizacja-05",
    category: "Zabudowy nietypowe",
    description: "Strefa dzienna z dużym stołem, zabudową telewizyjną i dekoracyjnym oświetleniem LED przy suficie.",
    coverImage: "/realizacje/realizacja-05.jpeg",
    coverFocalPoint: "center",
    tags: ["Salon", "Jadalnia", "Zabudowa RTV"],
    featured: true,
    order: 5,
    images: [
      image("realizacja-05.jpeg", {
        alt: "Salon z jadalnią, zabudową RTV i zielonym podświetleniem LED",
        caption: "Zabudowa strefy dziennej łącząca miejsce do rodzinnych spotkań z częścią telewizyjną.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-06",
    title: "Kuchnia otwarta na salon z liniowym światłem",
    slug: "realizacja-06",
    category: "Kuchnie",
    description: "Jasna kuchnia połączona ze strefą dzienną, uzupełniona geometrycznym oświetleniem sufitowym i akcentem LED.",
    coverImage: "/realizacje/realizacja-06.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Salon", "Oświetlenie LED"],
    featured: true,
    order: 6,
    images: [
      image("realizacja-06.jpeg", {
        alt: "Otwarta kuchnia z białymi frontami, czarnymi uchwytami i liniowym oświetleniem",
        caption: "Kuchnia otwarta na salon z dopracowanym układem szafek i dekoracyjną linią światła.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-07",
    title: "Zabudowa RTV z lamelami i zielonym LED",
    slug: "realizacja-07",
    category: "Zabudowy nietypowe",
    description: "Ściana telewizyjna z białymi szafkami, pionowymi lamelami i podświetleniem budującym klimat salonu.",
    coverImage: "/realizacje/realizacja-07.jpeg",
    coverFocalPoint: "center",
    tags: ["RTV", "Lamele", "Oświetlenie LED"],
    featured: true,
    order: 7,
    images: [
      image("realizacja-07.jpeg", {
        alt: "Zabudowa RTV z białymi szafkami, lamelami i zielonym podświetleniem LED",
        caption: "Nowoczesna zabudowa telewizyjna z miejscem do przechowywania i dekoracyjną linią LED.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-08",
    title: "Nowoczesna kuchnia z czarną zabudową AGD",
    slug: "realizacja-08",
    category: "Kuchnie",
    description: "Kuchnia na wymiar z kontrastem czarnych wysokich frontów, drewnianych akcentów i jasnej strefy roboczej.",
    coverImage: "/realizacje/realizacja-08.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Czarne fronty", "Drewniany akcent"],
    featured: true,
    order: 8,
    images: [
      image("realizacja-08.jpeg", {
        alt: "Nowoczesna kuchnia z czarną zabudową AGD, jasnymi szafkami i drewnianą ścianą",
        caption: "Kontrastowa kuchnia z wysoką zabudową AGD i ciepłym drewnianym wykończeniem.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-09",
    title: "Jasna kuchnia narożna z górną zabudową",
    slug: "realizacja-09",
    category: "Kuchnie",
    description: "Biała kuchnia na wymiar z pojemnymi szafkami górnymi, jasnym blatem i uporządkowaną strefą pracy.",
    coverImage: "/realizacje/realizacja-09.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Białe fronty", "Zabudowa narożna"],
    featured: true,
    order: 9,
    images: [
      image("realizacja-09.jpeg", {
        alt: "Biała kuchnia narożna z jasnym blatem i szafkami zabudowanymi do sufitu",
        caption: "Jasna kuchnia z dużą liczbą szafek i wygodnie zaplanowaną strefą roboczą.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },

  {
    id: "realizacja-10",
    title: "Szafy do przedpokoju z jasnymi frontami",
    slug: "realizacja-10",
    category: "Szafy i garderoby",
    description: "Zabudowa korytarza z wysokimi frontami, złotymi uchwytami i lustrzanym panelem powiększającym przestrzeń.",
    coverImage: "/realizacje/realizacja-10.jpeg",
    coverFocalPoint: "center",
    tags: ["Szafa", "Przedpokój", "Lustrzane fronty"],
    featured: true,
    order: 10,
    images: [
      image("realizacja-10.jpeg", {
        alt: "Jasne szafy w przedpokoju z długimi uchwytami i lustrzanym panelem",
        caption: "Zabudowa przedpokoju z pojemnymi szafami i eleganckim lustrzanym akcentem.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-11",
    title: "Drewniany stół do jadalni z miękkimi krzesłami",
    slug: "realizacja-11",
    category: "Zabudowy nietypowe",
    description: "Strefa jadalni z dużym stołem, dopasowaną kolorystyką drewna i eleganckim oświetleniem nad blatem.",
    coverImage: "/realizacje/realizacja-11.jpeg",
    coverFocalPoint: "center",
    tags: ["Jadalnia", "Stół drewniany", "Meble na wymiar"],
    featured: true,
    order: 11,
    images: [
      image("realizacja-11.jpeg", {
        alt: "Jadalnia z dużym drewnianym stołem, tapicerowanymi krzesłami i lampą nad blatem",
        caption: "Drewniany stół do jadalni zaprojektowany jako centralny element rodzinnej przestrzeni.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-12",
    title: "Kuchnia widziana przez portal lamelowy",
    slug: "realizacja-12",
    category: "Kuchnie",
    description: "Jasna kuchnia z drewnianymi akcentami, pokazana przez dekoracyjne lamele oddzielające strefę dzienną.",
    coverImage: "/realizacje/realizacja-12.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Lamele", "Jasne fronty"],
    featured: true,
    order: 12,
    images: [
      image("realizacja-12.jpeg", {
        alt: "Jasna kuchnia na wymiar za dekoracyjnym portalem z pionowych lameli",
        caption: "Dekoracyjne lamele tworzą miękkie przejście między kuchnią a częścią dzienną.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },

  {
    id: "realizacja-13",
    title: "Kuchnia z półwyspem i drewnianym blatem",
    slug: "realizacja-13",
    category: "Kuchnie",
    description: "Nowoczesna kuchnia na wymiar z białymi frontami, drewnianą płaszczyzną półwyspu i czarnymi detalami.",
    coverImage: "/realizacje/realizacja-13.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Półwysep", "Drewniany blat"],
    featured: true,
    order: 13,
    images: [
      image("realizacja-13.jpeg", {
        alt: "Biała kuchnia z drewnianym półwyspem, czarnymi lampami i wysoką zabudową AGD",
        caption: "Półwysep kuchenny łączy dodatkowy blat roboczy z miejscem na szybkie posiłki.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-14",
    title: "Kuchnia z lamelami i blatem w kolorze drewna",
    slug: "realizacja-14",
    category: "Kuchnie",
    description: "Widok na jasną kuchnię z drewnianym blatem, pionowymi lamelami i dopasowaną wysoką zabudową.",
    coverImage: "/realizacje/realizacja-14.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Lamele", "Drewniany blat"],
    featured: true,
    order: 14,
    images: [
      image("realizacja-14.jpeg", {
        alt: "Jasna kuchnia z drewnianym blatem, pionowymi lamelami i czarnymi lampami",
        caption: "Białe fronty i drewniany blat ocieplają nowoczesną kuchnię z lamelowym akcentem.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-15",
    title: "Detal lameli przy wejściu do kuchni",
    slug: "realizacja-15",
    category: "Lamele",
    description: "Zbliżenie na pionowe lamele, które porządkują przejście do kuchni i podkreślają wysokość wnętrza.",
    coverImage: "/realizacje/realizacja-15.jpeg",
    coverFocalPoint: "center",
    tags: ["Lamele", "Kuchnia", "Detal stolarski"],
    featured: true,
    order: 15,
    images: [
      image("realizacja-15.jpeg", {
        alt: "Pionowe lamele przy przejściu do jasnej kuchni z czarnymi lampami",
        caption: "Lamele wykonane na wymiar porządkują przejście i dodają wnętrzu rytmu.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },

  {
    id: "realizacja-16",
    title: "Zabudowa gospodarcza z blatem roboczym",
    slug: "realizacja-16",
    category: "Zabudowy nietypowe",
    description: "Praktyczna zabudowa z szafkami, blatem i otwartym modułem, zaplanowana do codziennego przechowywania.",
    coverImage: "/realizacje/realizacja-16.jpeg",
    coverFocalPoint: "center",
    tags: ["Zabudowa gospodarcza", "Przechowywanie", "Blat roboczy"],
    featured: true,
    order: 16,
    images: [
      image("realizacja-16.jpeg", {
        alt: "Jasna zabudowa gospodarcza z szafkami, blatem i otwartą wnęką na akcesoria",
        caption: "Funkcjonalna zabudowa gospodarcza z miejscem na przechowywanie i wygodnym blatem.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-17",
    title: "Sypialnia z łóżkiem pod skosem",
    slug: "realizacja-17",
    category: "Zabudowy nietypowe",
    description: "Łóżko i zabudowa sypialniana dopasowane do skosów, z miękkim wezgłowiem i uporządkowaną formą.",
    coverImage: "/realizacje/realizacja-17.jpeg",
    coverFocalPoint: "center",
    tags: ["Sypialnia", "Skosy", "Łóżko na wymiar"],
    featured: true,
    order: 17,
    images: [
      image("realizacja-17.jpeg", {
        alt: "Sypialnia na poddaszu z łóżkiem pod skosem i tapicerowanym wezgłowiem",
        caption: "Zabudowa sypialni wykorzystuje trudną przestrzeń pod skosami bez utraty lekkości.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-18",
    title: "Biała kuchnia z czarnym sprzętem AGD",
    slug: "realizacja-18",
    category: "Kuchnie",
    description: "Duża kuchnia na wymiar z białymi frontami, czarną lodówką, zabudowanym piekarnikiem i szerokim blatem.",
    coverImage: "/realizacje/realizacja-18.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Białe fronty", "AGD w zabudowie"],
    featured: true,
    order: 18,
    images: [
      image("realizacja-18.jpeg", {
        alt: "Biała kuchnia z czarną lodówką, zabudowanym piekarnikiem i jasnym blatem",
        caption: "Duża kuchnia z czytelnym podziałem na strefę przechowywania, gotowania i pracy.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-19",
    title: "Kuchnia z wysoką zabudową i wiszącymi lampami",
    slug: "realizacja-19",
    category: "Kuchnie",
    description: "Jasna kuchnia z zabudową AGD, drewnianym blatem i czarnymi lampami podkreślającymi strefę półwyspu.",
    coverImage: "/realizacje/realizacja-19.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Zabudowa AGD", "Lampy wiszące"],
    featured: true,
    order: 19,
    images: [
      image("realizacja-19.jpeg", {
        alt: "Kuchnia z wysoką zabudową AGD, drewnianym blatem i czarnymi lampami",
        caption: "Wysoka zabudowa porządkuje sprzęt AGD, a drewniany blat ociepla jasne fronty.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-20",
    title: "Szafa przesuwna z lustrzanymi frontami",
    slug: "realizacja-20",
    category: "Szafy i garderoby",
    description: "Szafa wnękowa z dużymi lustrami i czarnymi profilami, zaprojektowana do jasnego przedpokoju.",
    coverImage: "/realizacje/realizacja-20.jpeg",
    coverFocalPoint: "center",
    tags: ["Szafa przesuwna", "Lustro", "Przedpokój"],
    featured: true,
    order: 20,
    images: [
      image("realizacja-20.jpeg", {
        alt: "Szafa przesuwna z lustrzanymi frontami i czarnymi profilami w przedpokoju",
        caption: "Lustrzane fronty szafy powiększają optycznie przestrzeń i ukrywają pojemne wnętrze.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },

  {
    id: "realizacja-21",
    title: "Komoda z ryflowanym frontem na wysokich nogach",
    slug: "realizacja-21",
    category: "Detale",
    description: "Wolnostojąca komoda z jasnym ryflowaniem, czarnymi uchwytami i lekką konstrukcją na smukłych nogach.",
    coverImage: "/realizacje/realizacja-21.jpeg",
    coverFocalPoint: "center",
    tags: ["Komoda", "Ryflowany front", "Detal"],
    featured: true,
    order: 21,
    images: [
      image("realizacja-21.jpeg", {
        alt: "Komoda z ryflowanym frontem, czarnymi uchwytami i wysokimi nogami",
        caption: "Ryflowany front i smukłe nogi nadają komodzie lekkość mimo pojemnej konstrukcji.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-22",
    title: "Detal ryflowania komody",
    slug: "realizacja-22",
    category: "Detale",
    description: "Zbliżenie na bok komody z pionowym ryflowaniem, cienkim blatem i dopasowanymi metalowymi nogami.",
    coverImage: "/realizacje/realizacja-22.jpeg",
    coverFocalPoint: "center",
    tags: ["Komoda", "Ryflowanie", "Detal stolarski"],
    featured: true,
    order: 22,
    images: [
      image("realizacja-22.jpeg", {
        alt: "Zbliżenie na ryflowany bok komody z cienkim blatem i czarną nogą",
        caption: "Precyzyjnie wykonane ryflowanie buduje rytm frontu i boku komody.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-23",
    title: "Jasna kuchnia z półwyspem i czarną lodówką",
    slug: "realizacja-23",
    category: "Kuchnie",
    description: "Widok ogólny kuchni z białymi frontami, półwyspem, czarną lodówką i zabudowanym sprzętem AGD.",
    coverImage: "/realizacje/realizacja-23.jpeg",
    coverFocalPoint: "center",
    tags: ["Kuchnia", "Półwysep", "Czarne AGD"],
    featured: true,
    order: 23,
    images: [
      image("realizacja-23.jpeg", {
        alt: "Biała kuchnia z półwyspem, czarną lodówką i wysoką zabudową AGD",
        caption: "Przestronna kuchnia z półwyspem i wyraźnym kontrastem białych frontów oraz czarnego AGD.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-24",
    title: "Klasyczna komoda z białymi frontami",
    slug: "realizacja-24",
    category: "Detale",
    description: "Komoda z profilowanymi frontami, drewnianym blatem i dekoracyjnymi uchwytami w ciepłym odcieniu metalu.",
    coverImage: "/realizacje/realizacja-24.jpeg",
    coverFocalPoint: "center",
    tags: ["Komoda", "Białe fronty", "Drewniany blat"],
    featured: true,
    order: 24,
    images: [
      image("realizacja-24.jpeg", {
        alt: "Biała komoda z profilowanymi frontami, drewnianym blatem i ozdobnymi uchwytami",
        caption: "Klasyczna komoda łączy profilowane fronty z ciepłym drewnianym blatem.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
  {
    id: "realizacja-25",
    title: "Szafa przesuwna z czarnymi profilami",
    slug: "realizacja-25",
    category: "Szafy i garderoby",
    description: "Duża szafa przesuwna z jasnymi frontami, czarnymi ramami i zabudową dopasowaną do ściany.",
    coverImage: "/realizacje/realizacja-25.jpeg",
    coverFocalPoint: "center",
    tags: ["Szafa przesuwna", "Czarne profile", "Zabudowa wnękowa"],
    featured: true,
    order: 25,
    images: [
      image("realizacja-25.jpeg", {
        alt: "Duża szafa przesuwna z jasnymi frontami i czarnymi profilami przy ścianie",
        caption: "Szafa przesuwna z dużymi frontami porządkuje przechowywanie i zachowuje spokojną linię wnętrza.",
        focalPoint: "center",
      }, 1),
    ],
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
  },
];
