export type OfferItem = {
  label: string;
  href: string;
  description: string;
  image: string;
  imageAlt: string;
  imagePosition?: string;
  group: "meble" | "lamele" | "agd" | "plyty" | "materialy";
  iconName: string;
};

export const offerItems: OfferItem[] = [
  // MEBLE NA WYMIAR
  {
    label: "Meble na wymiar",
    href: "/oferta/meble-na-wymiar",
    description: "Kompleksowa realizacja mebli od pomiaru po montaż",
    image: "/client-assets/project-kitchen.jpg",
    imageAlt: "Nowoczesne meble kuchenne na wymiar",
    imagePosition: "center",
    group: "meble",
    iconName: "Home",
  },
  {
    label: "Meble kuchenne",
    href: "/oferta/meble-kuchenne",
    description: "Funkcjonalne kuchnie dopasowane do Twoich potrzeb",
    image: "/realizacje/realizacja-07.jpeg",
    imageAlt: "Zabudowa kuchenna na wymiar z AGD",
    imagePosition: "center",
    group: "meble",
    iconName: "ChefHat",
  },
  {
    label: "Meble łazienkowe",
    href: "/oferta/meble-lazienkowe",
    description: "Zabudowy łazienkowe odporne na wilgoć",
    image: "/realizacje/realizacja-01.jpeg",
    imageAlt: "Szafka łazienkowa z ryflowanymi frontami",
    imagePosition: "center",
    group: "meble",
    iconName: "Bath",
  },
  {
    label: "Meble biurowe",
    href: "/oferta/meble-biurowe",
    description: "Ergonomiczne meble do biur i gabinetów",
    image: "/client-assets/project-office.jpg",
    imageAlt: "Zabudowa gabinetowa z biurkiem i regałem",
    imagePosition: "center",
    group: "meble",
    iconName: "Briefcase",
  },
  {
    label: "Meble do salonu",
    href: "/oferta/meble-do-salonu",
    description: "Komody, szafki RTV i regały do pokoju dziennego",
    image: "/realizacje/realizacja-12.jpeg",
    imageAlt: "Nowoczesna szafka RTV na wymiar w salonie",
    imagePosition: "center",
    group: "meble",
    iconName: "Tv",
  },
  {
    label: "Meble do sypialni",
    href: "/oferta/meble-do-sypialni",
    description: "Łóżka, szafki nocne i toaletki",
    image: "/realizacje/realizacja-23.jpeg",
    imageAlt: "Sypialnia z tapicerowanym łóżkiem i szafą na wymiar",
    imagePosition: "center",
    group: "meble",
    iconName: "BedDouble",
  },
  {
    label: "Meble dziecięce",
    href: "/oferta/meble-do-pokoju-dzieciecego",
    description: "Bezpieczne i kreatywne meble dla najmłodszych",
    image: "/client-assets/meble-do-pokoju-dzieciecego.png",
    imageAlt: "Praktyczna zabudowa meblowa w pokoju dziecięcym",
    imagePosition: "center",
    group: "meble",
    iconName: "Smile",
  },
  {
    label: "Garderoby i szafy",
    href: "/oferta/garderoby",
    description: "Pojemne szafy wnękowe i garderoby na wymiar",
    image: "/realizacje/realizacja-32.jpeg",
    imageAlt: "Garderoba z przesuwnymi frontami",
    imagePosition: "center",
    group: "meble",
    iconName: "DoorClosed",
  },
  {
    label: "Zabudowy nietypowe",
    href: "/oferta/zabudowy-nietypowe",
    description: "Rozwiązania do trudnych wnęk i pod skosy",
    image: "/client-assets/meble-zabudowy-nietypowe.png",
    imageAlt: "Zabudowa wnękowa pod wymiar",
    imagePosition: "center",
    group: "meble",
    iconName: "Hammer",
  },
  {
    label: "Lite drewno i fornir",
    href: "/oferta/meble-z-litego-drewna-i-fornirowane",
    description: "Szlachetne meble z naturalnego drewna",
    image: "/realizacje/realizacja-17.jpeg",
    imageAlt: "Stół z litego drewna w jadalni",
    imagePosition: "center",
    group: "meble",
    iconName: "Trees",
  },

  // LAMELE
  {
    label: "Lamele",
    href: "/lamele",
    description: "Nowoczesne dekoracyjne panele ścienne",
    image: "/client-assets/lamele-glowna.png",
    imageAlt: "Nowoczesne lamele ścienne w aranżacji wnętrza",
    imagePosition: "center",
    group: "lamele",
    iconName: "PanelTop",
  },
  {
    label: "Lamele dla domu",
    href: "/lamele/klient-indywidualny",
    description: "Dekoracje ścienne do salonu, sypialni i przedpokoju",
    image: "/client-assets/lamele-dom.png",
    imageAlt: "Dekoracyjne lamele drewniane w domu",
    imagePosition: "center",
    group: "lamele",
    iconName: "Sparkles",
  },
  {
    label: "Sprzedaż hurtowa",
    href: "/lamele/sprzedaz-hurtowa",
    description: "Oferta lameli dla stolarzy, firm i inwestorów",
    image: "/client-assets/lamele-hurt.png",
    imageAlt: "Ekspozycja hurtowa lameli i paneli ściennych",
    imagePosition: "center",
    group: "lamele",
    iconName: "Boxes",
  },
  {
    label: "Lamele na wymiar",
    href: "/lamele/na-wymiar",
    description: "Panele lamelowe docięte na dokładną wysokość",
    image: "/client-assets/lamele-wymiar.png",
    imageAlt: "Montaż lameli na wymiar w pomieszczeniu",
    imagePosition: "center",
    group: "lamele",
    iconName: "Ruler",
  },
  {
    label: "Opłaszczowywanie",
    href: "/lamele/oplaszczowywanie-elementow",
    description: "Foliowanie profili w dowolnym kolorze i dekorze",
    image: "/client-assets/lamele-oplaszczowywanie.png",
    imageAlt: "Proces opłaszczowywania i foliowania lameli",
    imagePosition: "center",
    group: "lamele",
    iconName: "Layers3",
  },

  // AGD
  {
    label: "AGD w projektach",
    href: "/agd",
    description: "Profesjonalny dobór i montaż sprzętu AGD",
    image: "/realizacje/realizacja-14.jpeg",
    imageAlt: "Czarny sprzęt AGD wbudowany w jasne szafki",
    imagePosition: "center",
    group: "agd",
    iconName: "MonitorCog",
  },
  {
    label: "AGD do zabudowy",
    href: "/agd/do-zabudowy",
    description: "Ergonomiczne wbudowanie lodówek, zmywarek i piekarników",
    image: "/realizacje/realizacja-11.jpeg",
    imageAlt: "Piekarnik i mikrofala w zabudowie słupkowej",
    imagePosition: "center",
    group: "agd",
    iconName: "Grid2X2",
  },
  {
    label: "AGD wolnostojące",
    href: "/agd/wolnostojace",
    description: "Planowanie przestrzeni pod sprzęt wolnostojący",
    image: "/realizacje/realizacja-29.jpeg",
    imageAlt: "Kuchnia z czarną lodówką wolnostojącą",
    imagePosition: "center",
    group: "agd",
    iconName: "Refrigerator",
  },
  {
    label: "Małe AGD",
    href: "/agd/male-agd",
    description: "Organizacja stref dla ekspresów i robotów kuchennych",
    image: "/realizacje/realizacja-08.jpeg",
    imageAlt: "Akcesoria kuchenne na blacie roboczym",
    imagePosition: "center",
    group: "agd",
    iconName: "PackageCheck",
  },
  {
    label: "Producenci AGD",
    href: "/agd/producenci-agd",
    description: "Sprzęt sprawdzonych marek w najlepszych cenach",
    image: "/realizacje/realizacja-24.jpeg",
    imageAlt: "Wyposażenie kuchenne AGD premium",
    imagePosition: "center",
    group: "agd",
    iconName: "Cpu",
  },

  // USŁUGI PŁYTOWE
  {
    label: "Usługi płytowe",
    href: "/uslugi-plytowe",
    description: "Kompleksowa obróbka płyt wiórowych i MDF",
    image: "/client-assets/uslugi-plytowe.png",
    imageAlt: "Praca stolarska z płytami",
    imagePosition: "center",
    group: "plyty",
    iconName: "Package",
  },
  {
    label: "Cięcie płyt",
    href: "/uslugi-plytowe/ciecie-plyt",
    description: "Precyzyjne formatowanie płyt na nowoczesnej pile",
    image: "/client-assets/ciecie-plyt.png",
    imageAlt: "Cięcie płyt meblowych",
    imagePosition: "center",
    group: "plyty",
    iconName: "ScanLine",
  },
  {
    label: "Oklejanie płyt",
    href: "/uslugi-plytowe/oklejanie-plyt",
    description: "Oklejanie wąskich krawędzi obrzeżem ABS i PUR",
    image: "/client-assets/oklejanie-plyt.png",
    imageAlt: "Precyzyjnie wykończona krawędź blatu",
    imagePosition: "center",
    group: "plyty",
    iconName: "SlidersHorizontal",
  },

  // MATERIAŁY I FRONTY
  {
    label: "Materiały i fronty",
    href: "/materialy-i-fronty",
    description: "Szeroki wybór płyt, blatów i frontów",
    image: "/client-assets/materialy-glowna.png",
    imageAlt: "Kolekcja materiałów i frontów meblowych Kower",
    imagePosition: "center",
    group: "materialy",
    iconName: "Palette",
  },
  {
    label: "Płyta wiórowa",
    href: "/materialy-i-fronty/plyta-wiorowa",
    description: "Trwała baza do produkcji korpusów meblowych",
    image: "/client-assets/materialy-wiorowa.png",
    imageAlt: "Korpusy meblowe wykonane z płyty wiórowej laminowanej",
    imagePosition: "center",
    group: "materialy",
    iconName: "FileSpreadsheet",
  },
  {
    label: "Płyta MDF",
    href: "/materialy-i-fronty/plyta-mdf",
    description: "Idealny materiał na fronty lakierowane i frezowane",
    image: "/client-assets/materialy-mdf.png",
    imageAlt: "Szafy meblowe wykonane z płyty MDF",
    imagePosition: "center",
    group: "materialy",
    iconName: "Layers",
  },
  {
    label: "Blaty laminowane",
    href: "/materialy-i-fronty/blaty-laminowane",
    description: "Wytrzymałe blaty w setkach dekorów Egger i Pfleiderer",
    image: "/client-assets/materialy-laminowane.png",
    imageAlt: "Wytrzymały blat laminowany w meblach kuchennych",
    imagePosition: "center",
    group: "materialy",
    iconName: "Grid",
  },
  {
    label: "Blaty kompaktowe",
    href: "/materialy-i-fronty/blaty-kompaktowe",
    description: "Cienkie, wodoodporne blaty HPL o grubości 12mm",
    image: "/client-assets/materialy-kompaktowe.png",
    imageAlt: "Nowoczesny, cienki blat kompaktowy w kuchni",
    imagePosition: "center",
    group: "materialy",
    iconName: "Maximize2",
  },
  {
    label: "Blaty z litego drewna",
    href: "/materialy-i-fronty/blaty-z-litego-drewna",
    description: "Naturalne, olejowane blaty dębowe i jesionowe",
    image: "/client-assets/materialy-lite-drewno.png",
    imageAlt: "Naturalne, olejowane blaty dębowe i jesionowe",
    imagePosition: "center",
    group: "materialy",
    iconName: "Flame",
  },
  {
    label: "Fronty lakierowane",
    href: "/materialy-i-fronty/fronty-lakierowane",
    description: "Eleganckie wykończenie w mat, półmat lub połysk",
    image: "/client-assets/materialy-lakierowane.png",
    imageAlt: "Eleganckie wykończenie w mat, półmat lub połysk",
    imagePosition: "center",
    group: "materialy",
    iconName: "Sparkles",
  },
  {
    label: "Fronty akrylowe",
    href: "/materialy-i-fronty/fronty-akrylowe",
    description: "Supermatowe i głęboko połyskowe fronty o wysokiej odporności",
    image: "/client-assets/materialy-akrylowe.png",
    imageAlt: "Supermatowe i głęboko połyskowe fronty o wysokiej odporności",
    imagePosition: "center",
    group: "materialy",
    iconName: "Sun",
  },
  {
    label: "Fronty ryflowane",
    href: "/materialy-i-fronty/fronty-ryflowane",
    description: "Modne, trójwymiarowe wzory frezowane w MDF",
    image: "/client-assets/materialy-ryflowane.png",
    imageAlt: "Modne, trójwymiarowe wzory frezowane w MDF",
    imagePosition: "center",
    group: "materialy",
    iconName: "AlignJustify",
  },
  {
    label: "Fronty tłoczone",
    href: "/materialy-i-fronty/fronty-tloczone",
    description: "Klasyczne i nowoczesne wzory frontów foliowanych",
    image: "/client-assets/materialy-tloczone.png",
    imageAlt: "Klasyczne i nowoczesne wzory frontów foliowanych",
    imagePosition: "center",
    group: "materialy",
    iconName: "FolderOpen",
  },
  {
    label: "Producenci płyt",
    href: "/materialy-i-fronty/producenci-plyt-meblowych",
    description: "Materiały od renomowanych marek Egger, Pfleiderer i Cleaf",
    image: "/client-assets/materialy-producenci-plyt.png",
    imageAlt: "Wzorniki płyt meblowych i frontów",
    imagePosition: "center",
    group: "materialy",
    iconName: "Award",
  },
  {
    label: "Partnerzy",
    href: "/producenci-i-partnerzy",
    description: "Współpraca z liderami rynku stolarskiego i okuć",
    image: "/client-assets/materialy-partnerzy.png",
    imageAlt: "Materiały i okucia Blum",
    imagePosition: "center",
    group: "materialy",
    iconName: "Handshake",
  },
];
